---
abstract: 'easy HTTP response object maker functions'
author:
  - 'motemen <motemen@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTTP-Response-Maker
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Class::Load: 0
  HTTP::Status: 0
  Sub::Name: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/motemen/HTTP-Response-Maker.git
version: 0.01
